- server/src/main/java/com/mainproject/server/audit/Auditable.java
- server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
- server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
- server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
- server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
- server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
- server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
- server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
- server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
- server/src/main/java/com/mainproject/server/utils/CustomBeanUtils.java
- server/src/main/java/com/mainproject/server/validator/NotSpace.java
- server/src/main/java/com/mainproject/server/validator/NotSpaceValidator.java
회원 수정 기능 구현, 회원 수정 비지니스 로직 예외 추가, beanUtils 추가
> "#25 [BE] feat: 회원 수정 기능 구현

- server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
- server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
> #38 [BE] feat: 마이 페이지 회원 정보 조회

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/GlobalStyle.js
- client/src/components/Container.js
- client/src/components/FlexBoxs.js
- client/src/components/common/Button.js
- client/src/components/common/ProfileImage.js
- client/src/components/findMate/FindMateTab.js
- client/src/components/findMate/MatePostCard.js
- client/src/components/findMate/MatePostList.js
- client/src/components/findMate/MatePostsContent.js
- client/src/components/findMate/SearchAddressBox.js
- client/src/pages/FindMatePage.js
- client/src/static/dummyData.js
- client/src/style/styleUtils.js
- client/src/style/styleVariable.js
#43 
버튼  컴포넌트, flex box 컴포넌트 구현
> #43 Fe/feat/43 find mate UI

- client/src/App.js
- client/src/GlobalStyle.js
- client/src/components/Container.js
- client/src/components/Header.js
- client/src/components/common/ProfileImage.js
- client/src/components/common/Title.js
- client/src/components/findMate/UserFilterForm.js
- client/src/components/findMate/UserFilterModal.js
- client/src/components/header/HeaderMyPageBox.js
- client/src/components/header/HeaderNav.js
- client/src/hooks/useOnClickOutside.js
- client/src/pages/FindMatePage.js
- client/src/pages/MainPage.js
#72 
헤더 마크업
모든 페이지의 상단에 떠있다.
왼쪽에는 메인 페이지로 갈 수 있는 로고 버튼이 있다.
오른쪽에는 다른 페이지로 이동할 수 있는 네비게이션 바가 있다.
- (로그인X) 메이트 찾기, 로그인 링크
- (로그인) 메이트 찾기, 채팅, 마이페이지 링크 / 로그아웃 버튼
---
> [FE] design: Header 마크업

- client/src/components/common/Title.js
- client/src/components/findMate/UserFilterForm.js
- client/src/components/findMate/UserFilterModal.js
> [FE] design: 상세 조건 모달 마크업

- client/public/index.html
- client/src/App.js
- client/src/GlobalStyle.js
- client/src/components/Container.js
- client/src/components/chatting/Chat.js
- client/src/components/chatting/ChatList.js
- client/src/components/chatting/ChatRoom.js
- client/src/components/chatting/ChattingArea.js
- client/src/components/chatting/MyChat.js
- client/src/components/common/ProfileImage.js
- client/src/pages/ChattingPage.js
- client/src/static/dummyData.js
#81 
- 전체적인 레이아웃
- 채팅 목록
- 채팅 Input
- 나의 채팅
- 상대방의 채팅
> 채팅 페이지 마크업

- server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
- server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
- server/src/main/java/com/mainproject/server/auth/userdetails/MemberDetails.java
- server/src/main/java/com/mainproject/server/auth/userdetails/MemberDetailsService.java
- server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
- server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
- server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
- server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
- server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
- server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
- server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
- server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
- server/src/main/resources/application-hr.yml
updatepet() 진행 후 반환하는 Response에 member 정보가 null로 들어가는 문제가 있음
> #76 [BE]fix: board, pet 회원 정보 적용 완료

- server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
- server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
- server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
- server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
- server/src/main/java/com/mainproject/server/domain/comments/repository/CommentsRepository.java
- server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
댓글을 달 경우 작성순으로 정렬이 되며,
특정 댓글의 대댓글을 작성할 경우 댓글 아래로 정렬이 됩니다.
> #63 [BE]feat: 댓글, 대댓글 정렬 완료

- client/public/index.html
- client/src/GlobalStyle.js
- client/src/components/Button.js
- client/src/components/matePost/Comment.js
- client/src/components/matePost/Map.js
- client/src/pages/PostDetailPage.js
- client/src/pages/PostEditPage.js
- client/src/pages/PostPage.js
- client/src/static/dummyData.js
- client/src/utils/dateConvert.js
> #42 [FE] design: 모임 글 상세 페이지 마크업 수정

- client/package-lock.json
- client/package.json
- client/public/index.html
- client/src/components/matePost/Map.js
- client/src/components/matePost/MapContainer.js
- client/src/pages/PostDetailPage.js
- client/src/pages/PostEditPage.js
- client/src/pages/PostPage.js
> [FEAT] 지도 API 적용

- server/src/main/resources/application-server.yml
- server/src/main/resources/logback-spring.xml
application-server.yml 수정, logback-spring.xml 설정 수정, 회원 동 주소 반환 로직 추가
> [BE] deploy: 배포

- client/src/App.js
- client/src/api/board/comment.js
- client/src/api/board/findMate.js
- client/src/api/loginInfo.js
- client/src/components/DeleteModal.js
- client/src/components/boardDetail/AddComment.js
- client/src/components/boardDetail/AddRecomment.js
- client/src/components/boardDetail/Comment.js
- client/src/components/boardDetail/CommentContainer.js
- client/src/components/boardDetail/Map.js
- client/src/components/boardDetail/Recomment.js
- client/src/components/boardDetail/RecommentList.js
- client/src/components/findMate/MateBoardCard.js
- client/src/pages/BoardDetailPage.js
- client/src/pages/BoardPage.js
> [FE] feat: 댓글 및 대댓글 기능 구현

- client/src/api/pet/pet.js
- client/src/components/myPage/PetInfo.js
- client/src/components/myPage/PetInfoInput.js
- client/src/components/myPage/PetList.js
> [FEAT] 강아지 리스트 추가/수정 에 react-query 적용

- client/package-lock.json
- client/package.json
- client/src/pages/BoardDetailPage.js
- 글 모집중일때 작성자만 수정&삭제 가능
- 글 모집마감일때 작성자만 삭제 가능 (수정 불가)
> [FE] fix: 글 상세 페이지 수정&삭제 버튼 권한 수정

- client/src/components/boardDetail/BoardMeetInfo.js
- client/src/components/findMate/MateBoardCard.js
- client/src/utils/dateConvert.js
- 모임 글 상세 페이지, 리스트 페이지 시간 한국 시간 기준으로 수정
> [FE] fix: 시간 오류 수정

- client/src/components/boardDetail/Comment.js
- client/src/components/boardDetail/Recomment.js
- 댓글과 대댓글 작성 시간 수정
- 댓글과 대댓글 작성자만 수정, 삭제 가능하게 수정
> [FE] fix: 댓글 & 대댓글 작성 시간 및 수정, 삭제 권한 수정

- client/src/components/GetDogInfo.js
> [FE] fix: 글 수정 페이지 URL 오류 수정

- client/src/components/boardDetail/Comment.js
- client/src/components/boardDetail/Recomment.js
- 댓글/대댓글 프로필 사진 수정
- 유저 프로필 사진 클릭 시 모달창에 멤버 아이디 값 넘기기
> [FE] fix: 댓글 & 대댓글 프로필 사진 수정

- client/src/components/boardDetail/MapContainer.js
- client/src/pages/BoardPage.js
- 문제점: 글 작성 시 아무것도 입력 안 해도 등록되는 오류 수정
- 해결: 제목, 내용, 데리고 갈 친구, 날짜, 장소 모두 필수 입력값으로 지정
> [FE] fix: 글 작성 시 입력값 필수로 지정

- client/src/components/login/LoginForm.js
- client/src/components/login/LoginModal.js
> [FE] feat: 게스트 로그인
